name: WooMinecraft
main: com.plugish.WooMinecraft.WooMinecraft
version: 1.0.2
author: JerryWood
description: This is a description.
website:  http://plugish.com

commands:
  woo:
    description: Reload settings
    usage: Syntax Error! /<command> [reload/register/check] - Reload the plugin, register a key, or check for donations.
    permission:  <plugin name>.admin